name: ddns_client
version: 2.0.0
description: >
  A library for checking the public internet address
  and updating a dynamic DNS entry.
homepage: https://github.com/danrubel/ddns_client.dart
environment:
  sdk: '>=2.12.0 <3.0.0'
dependencies:
  logging: ^1.0.1
  collection: ^1.15.0-nullsafety.4
dev_dependencies:
  test: ^1.15.3
  yaml: ^3.0.0
