name: ddns_client
version: 1.0.1
description: >
  A library for checking the public internet address
  and updating a dynamic DNS entry.
homepage: https://github.com/danrubel/ddns_client.dart
environment:
  sdk: '>=2.8.4 <3.0.0'
dependencies:
  logging: ^0.11.4
dev_dependencies:
  test: ^1.15.3
  yaml: ^2.0.0
