name: ddns_client
version: 0.8.0
description: >
  A library for checking the public internet address
  and updating a dynamic DNS entry.
author: Dan Rubel <danrubel@google.com>
homepage: https://github.com/danrubel/dart_ddns_client
environment:
  sdk: '>=1.0.0 <2.0.0'
dependencies:
  logging: ">=0.9.1 <0.10.0"
dev_dependencies:
  unittest: ">=0.11.4 <0.12.0"
  grinder: '>=0.7.0 <0.8.0'
